TURO_USERNAME = 'your_email_address_here'
TURO_PASSWORD = 'your_password_here'

driverLocation = 'the_path_to_chrome_webdriver'

fieldnames=['DROPOFF','GUEST','TRIP TOTAL','URL','YOU EARNED','MILES INCLUDED','TURO FEES','TRIP PRICE','PICKUP','MILES DRIVEN','ADDITIONAL MILES DRIVEN','TOLLS','TOTAL MILES','CLEANING','EXCESS DISTANCE REIMBURSEMENT','EXCESS MILES','DISCOUNT','REIMBURSEMENT TOTAL','DELIVERY FEE','LATE FEE','CONVENIENCE FEE','GAS','ADDITIONAL USAGE','SMOKING']